/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProjectionsRouteImport } from './routes/_app/projections'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectionsRoute = AppProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/categories': typeof AppCategoriesRoute
  '/projections': typeof AppProjectionsRoute
  '/reports': typeof AppReportsRoute
  '/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesByTo {
  '/categories': typeof AppCategoriesRoute
  '/projections': typeof AppProjectionsRoute
  '/reports': typeof AppReportsRoute
  '/transactions': typeof AppTransactionsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/projections': typeof AppProjectionsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categories' | '/projections' | '/reports' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/categories' | '/projections' | '/reports' | '/transactions' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/categories'
    | '/_app/projections'
    | '/_app/reports'
    | '/_app/transactions'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projections': {
      id: '/_app/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof AppProjectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppProjectionsRoute: typeof AppProjectionsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppProjectionsRoute: AppProjectionsRoute,
  AppReportsRoute: AppReportsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
